import type { GitHubPRFile } from '../../types/github';
import type { ReviewFinding } from '../../types/review';
import { logger } from '../logger';

/**
 * Interface for static analysis plugins that run before the LLM.
 * These catch deterministic issues (console.logs, missing awaits, etc)
 * with zero token cost.
 */
export interface StaticPlugin {
    name: string;
    /** Returns findings generated by this plugin */
    run(files: GitHubPRFile[]): ReviewFinding[];
}

import { SuspiciousPatternsPlugin } from './suspicious';
import { TsStrictPlugin } from './ts-strict';
import { SecretsScannerPlugin } from './secrets';

/** All registered deterministic plugins */
export const plugins: StaticPlugin[] = [
    new SuspiciousPatternsPlugin(),
    new TsStrictPlugin(),
    new SecretsScannerPlugin(),
];

/**
 * Runs all static plugins over the reviewable files.
 * Returns an aggregated list of deterministic findings.
 */
export function runStaticPlugins(files: GitHubPRFile[]): ReviewFinding[] {
    const findings: ReviewFinding[] = [];
    for (const plugin of plugins) {
        try {
            findings.push(...plugin.run(files));
        } catch (err) {
            // Plugins must not crash the pipeline
            logger.error(`Plugin ${plugin.name} crashed`, err instanceof Error ? err : undefined);
        }
    }
    return findings;
}
